apiVersion: v1
kind: Service
metadata:
  name: my-node-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30002  # Change this to an unused port
  selector:
    app: my-node-app
